from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, overload

import torch

from .hydro import HydroOptions
from .layout import Layout, LayoutOptions, SyncOptions
from .reconstruction import ReconstructOptions
from .riemann import RiemannSolverOptions

bcfunc_t = Optional[Callable[[torch.Tensor, int, "BoundaryFuncOptions"], None]]
Variables = Dict[str, torch.Tensor]
MeshVariables = List[Variables]


class ScalarOptions:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    @overload
    def verbose(self) -> bool: ...
    @overload
    def verbose(self, value: bool) -> "ScalarOptions": ...

    @overload
    def nvar(self) -> int: ...
    @overload
    def nvar(self, value: int) -> "ScalarOptions": ...

    @overload
    def names(self) -> List[str]: ...
    @overload
    def names(self, value: List[str]) -> "ScalarOptions": ...

    @overload
    def recon(self) -> ReconstructOptions: ...
    @overload
    def recon(self, value: ReconstructOptions) -> "ScalarOptions": ...

    @overload
    def riemann(self) -> RiemannSolverOptions: ...
    @overload
    def riemann(self, value: RiemannSolverOptions) -> "ScalarOptions": ...


class MeshBlockOptions:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    @staticmethod
    def from_yaml(filename: str, verbose: bool = False) -> "MeshBlockOptions": ...

    def set_bfunc(self, dx3: int, dx2: int, dx1: int, func: bcfunc_t) -> None: ...

    @overload
    def verbose(self) -> bool: ...
    @overload
    def verbose(self, value: bool) -> "MeshBlockOptions": ...

    @overload
    def basename(self) -> str: ...
    @overload
    def basename(self, value: str) -> "MeshBlockOptions": ...

    @overload
    def output_dir(self) -> str: ...
    @overload
    def output_dir(self, value: str) -> "MeshBlockOptions": ...

    @overload
    def outputs(self): ...
    @overload
    def outputs(self, value) -> "MeshBlockOptions": ...

    @overload
    def intg(self): ...
    @overload
    def intg(self, value) -> "MeshBlockOptions": ...

    @overload
    def coord(self): ...
    @overload
    def coord(self, value) -> "MeshBlockOptions": ...

    @overload
    def hydro(self) -> HydroOptions: ...
    @overload
    def hydro(self, value: HydroOptions) -> "MeshBlockOptions": ...

    @overload
    def scalar(self) -> ScalarOptions: ...
    @overload
    def scalar(self, value: ScalarOptions) -> "MeshBlockOptions": ...

    @overload
    def ib(self): ...
    @overload
    def ib(self, value) -> "MeshBlockOptions": ...

    @overload
    def bfuncs(self) -> List[bcfunc_t]: ...
    @overload
    def bfuncs(self, value: List[bcfunc_t]) -> "MeshBlockOptions": ...

    @overload
    def layout(self) -> LayoutOptions: ...
    @overload
    def layout(self, value: LayoutOptions) -> "MeshBlockOptions": ...


class MeshOptions:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def set_local_horizontal_cells(self, nx2: int, nx3: int) -> None: ...

    @overload
    def block(self) -> MeshBlockOptions: ...
    @overload
    def block(self, value: MeshBlockOptions) -> "MeshOptions": ...

    @overload
    def blocks_per_process(self) -> int: ...
    @overload
    def blocks_per_process(self, value: int) -> "MeshOptions": ...


class MeshBlock:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, options: MeshBlockOptions) -> None: ...

    options: MeshBlockOptions

    def __repr__(self) -> str: ...
    def module(self, name: str) -> torch.nn.Module: ...
    def buffer(self, name: str) -> torch.Tensor: ...
    def cycle(self) -> int: ...
    def inc_cycle(self) -> int: ...
    def set_user_output_func(self, func: Callable[[Variables], Variables]) -> None: ...
    def set_user_stage_forcings(self, filenames: Sequence[str]) -> None: ...
    def get_layout(self) -> Layout: ...

    def forward(self, vars: Variables, dt: float, stage: int) -> None: ...
    def advance_local(self, vars: Variables, dt: float, stage: int) -> None: ...
    def max_time_step(self, vars: Variables) -> float: ...
    def local_max_time_step(self, vars: Variables) -> float: ...
    def make_outputs(self, vars: Variables, time: float, final_write: bool = False) -> None: ...
    def print_cycle_info(self, vars: Variables, time: float, dt: float) -> None: ...
    def finalize(self, vars: Variables, time: float) -> None: ...
    def check_redo(self, vars: Variables) -> int: ...
    def get_outputs(self): ...
    def exchange_ghost_zones(self, vars: Variables) -> None: ...

    def part(
        self,
        offset: Tuple[int, int, int],
        exterior: bool = True,
        extend_x1: int = 0,
        extend_x2: int = 0,
        extend_x3: int = 0,
    ) -> Tuple[slice, ...]: ...

    def initialize(self, vars: Variables) -> Tuple[Variables, float]: ...
    def initialize_from_restart(self, restart_file: str) -> Tuple[Variables, float]: ...
    def initialize_local(self, vars: Variables) -> None: ...
    def initialize_under_mesh(self, vars: Variables) -> None: ...
    def finalize_initialization(self, vars: Variables) -> None: ...
    def apply_hydro_bc(self, var: torch.Tensor, type: int = ...) -> None: ...


class Mesh:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, options: MeshOptions) -> None: ...

    @staticmethod
    def from_yaml(filename: str, verbose: bool = False) -> "Mesh": ...

    options: MeshOptions
    blocks: Sequence[MeshBlock]

    def __repr__(self) -> str: ...
    def module(self, name: str) -> torch.nn.Module: ...
    def buffer(self, name: str) -> torch.Tensor: ...
    def forward(self, vars: MeshVariables, dt: float, stage: int) -> None: ...
    def initialize(
        self, vars: MeshVariables, restart_files: Sequence[str] = ...
    ) -> Tuple[MeshVariables, float]: ...
    def max_time_step(self, vars: MeshVariables) -> float: ...
    def exchange(self, vars: MeshVariables, opts: SyncOptions) -> None: ...
    def exchange_ghost_zones(self, vars: MeshVariables, type: int = ...) -> None: ...
    def set_user_stage_forcings(self, filenames: Sequence[str]) -> None: ...
    def make_outputs(
        self, vars: MeshVariables, current_time: float, final_write: bool = False
    ) -> None: ...
    def print_cycle_info(self, vars: MeshVariables, time: float, dt: float) -> None: ...
    def check_redo(self, vars: MeshVariables) -> int: ...
    def set_cycle(self, cycle: int) -> None: ...
    def finalize(self, vars: MeshVariables, time: float) -> None: ...
